### ISSUE TITLE
[nats] jetstream driver `ensureStream` returns misleading error

### ISSUE THREAD

**Issue by olpie101** [modernice/goes#115]
The `ensureStream` method of the JetStream driver returns a misleading error when the stream configuration is not as expected. It returns the `ErrConsumerExists` error instead of `ErrStreamExists`
[source](https://github.com/modernice/goes/blob/main/backend/nats/jetstream.go#L281)

I would be happy to create PR.

**Comment by bounoable** [comment]
Nice catch, will merge your PR if you want to fix this!
