### ISSUE TITLE
Return copy of slice

### ISSUE THREAD

**Issue by bounoable** [modernice/goes#155]
The caller shouldn't be able to modify underlying array of the internal insertedEvents slice:

https://github.com/modernice/goes/blob/875903b43ae7ae6237efd5d1b1ac556c67ad91c9/backend/mongo/transaction.go#L56

**Comment by rafiramadhana** [comment]
hi @bounoable can I work on this? thanks

**Comment by bounoable** [comment]
hey @rafiramadhana, that would be nice 👍🏼

**Comment by bounoable** [comment]
oh, seems like someone already did 😄
